Add support for round towards odd
openhwgroup/cvfpu pull request #70
Opened 2023-01-23 08:35 UTC by Shafi10x

Added support for round-towards-odd.

2023-01-23 11:02 UTC, pascalgouedo approved these changes
Seems ok to me as long as it is CV-FPU related only and Cores using it stick to RISC-V F spec as of today, i.e. not being able to use this new rounding mode.

2023-01-24 06:26 UTC, Shafi10x commented
Can we merge this?

2023-01-24 08:44 UTC, pascalgouedo commented
Guess waiting @stmach feedback ...

2023-01-24 09:25 UTC, stmach requested changes
What is the use case of this new rounding mode? (i.e., where is it used?)
In any case, please consider the suggested implementation.

2023-01-24 09:25 UTC, stmach commented on src/fpnew_rounding.sv
>        default: round_up = fpnew_pkg::DONT_CARE; // propagate x
Why not just handle it here instead of adding a mux to the result? Keep in mind the added HW will not be optimized away from cores not being able to use the new rounding mode.
```suggestion
      fpnew_pkg::ROD: round_up = ~abs_value_i[0] & (| round_sticky_bits_i);
      default: round_up = fpnew_pkg::DONT_CARE; // propagate x
```

2023-01-24 09:25 UTC, stmach commented on src/fpnew_rounding.sv
> +  assign abs_value_rod = {abs_value_i[AbsWidth-1:1],abs_value_i[0] || (|round_sticky_bits_i)};
```suggestion
```

2023-01-24 09:25 UTC, stmach commented on src/fpnew_rounding.sv
> +
```suggestion
```

2023-01-24 09:25 UTC, stmach commented on src/fpnew_rounding.sv
> +  assign abs_rounded_o =(rnd_mode_i == fpnew_pkg::ROD)? abs_value_rod : abs_value_i + round_up;
```suggestion
  assign abs_rounded_o = abs_value_i + round_up;
```

2023-01-24 10:26 UTC, Shafi10x commented
@stmach This mode is required for a vector narrowing instruction.i.e **vfncvt.rod.f.fw** .

2023-01-26 11:09 UTC, Shafi10x commented
@stmach I have updated the changes according to your suggestions. Is there anything else that needs to be changed?

2023-01-26 12:43 UTC, stmach approved these changes

2023-01-30 07:04 UTC, Shafi10x commented
Can we merge this?

2023-01-30 08:40 UTC, pascalgouedo commented
Hi @MikeOpenHWGroup @davideschiavone @DBees 

It seems cv-fpu repo is not in the list of the ones I have any right unlike cv32e40p or core-v-verif.
I can't add reviewers, put labels or merge a pull-request.

So either it needs to be added on my list or anyone having rights on it will have to do this merge.

Cheers,
Pascal.

2023-01-30 09:02 UTC, MikeOpenHWGroup commented
Hi @pascalgouedo, please try it now.

2023-01-30 09:19 UTC, pascalgouedo commented
LGTM

2023-01-30 09:20 UTC, merged

2023-01-30 09:30 UTC, pascalgouedo commented
Hi @Shafi10x 

I didn't figure out that you made your pull request to the vec branch of cvfpu rather than develop.

Could you please make a new pull request with your updates with respect to up-to-date develop branch ?

Best regards,
Pascal.

2023-01-31 11:00 UTC, mp-17 commented
Hello everyone! Thanks for merging this @pascalgouedo. 
Do you want to merge the `ROD` rounding mode also in the `develop` branch? We targeted `vec` since it's the branch we are using with our Vector Unit (Ara).

2023-01-31 11:34 UTC, pascalgouedo commented
Hi @mp-17 
Yes I saw afterwards that there are different branches which seem not aligned.
develop has some commits after a 0.6.6 release merge while vec has **different** commits after 0.6.2 release.

I though that like in cv32e40p repo, develop is always up-to-date and that all other branches are pushing all their modifications to develop and are merged down from develop when other branches make updates.
That's why I asked to make a new PR (#71) to merge your #70 updates to develop.
But I was maybe wrong to ask that...

I let @lucabertaccini / @stmach decide if we need to execute #71 or not (anyway it seems I can not do it because I am not an authorized user to merge on base branch).

But a the end of the day we need to clarify all together the future merging methodology of cvfpu base branch.

Best regards,
Pascal.

2023-01-31 11:45 UTC, mp-17 commented
Thus far, we have been using `vec` as a stable branch to deploy our vector system, and the changes were not meant to be merged in the `develop` branch. But I think we can discuss this and, in the future, make `vec` converge. 
We had a similar situation with the `cva6` core: we used an old and not aligned branch, and we are trying to converge to the upstream OpenHW Group's version to reduce dispersion.